---
# ensure number of instances running with a tag matches exact_count
    

- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "target"
    instance_type: "{{ supriya }}"
    security_group: launch-wizard-8
    region: eu-central-1
    aws_access_key: "{{ec2_access_key}}"  # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined 
    network_interfaces:
      - assign_public_ip: true
    image_id: "{{ item.image }}"
    tags:
      Environment: "{{ item.name }}"
  loop:
  - { image: "ami-007c3072df8eb6584", name: "centos" }
  - { image: "ami-0084a47cc718c111a", name: "ubuntu-1" }
  - { image: "ami-0084a47cc718c111a", name: "ubuntu-2" }
